android: freedreno/ir3: fix Makefile.sources and include src/util
Fixes the following building errors:

clang: error: no such file or directory: 'external/mesa/src/freedreno/ir3/ir3_group.c'
clang: error: no input files

external/mesa/src/freedreno/ir3/ir3_cse.c:27:10: fatal error: 'xxhash.h' file not found
         ^~~~~~~~~~
1 error generated.

external/mesa/src/freedreno/ir3/ir3_dominance.c:27:10: fatal error: 'ralloc.h' file not found
         ^~~~~~~~~~
1 error generated.

Fixes: d4b5a550ede ("ir3: Add dominance infrastructure")
Fixes: 3ac743c333e ("ir3: Add pass to lower arrays to SSA")
Fixes: 0ffcb19b9d9 ("ir3: Rewrite register allocation")
Fixes: 2f51379d036 ("ir3/ra: Add a validation pass")
Fixes: fa17295ebdd ("ir3: Add simple CSE pass")