mesa: remove deprecated arch.arm.neon cflags
Android 15 QPR2 Soong no longer recognizes the arch.arm.neon
property in cc modules, causing build failures during Soong
bootstrap.

Replace the nested arch.arm.neon.cflags with arch.arm.cflags
to restore compatibility with the updated Soong parser.

This change is safe since the NO_FORMAT_ASM define can apply
to all ARM builds.

Fixes:
error: unrecognized property "arch.arm.neon.cflags"

Signed-off-by: Jackeagle <jackeagle102@gmail.com>